language: ruby

rvm:
  - 1.9.3

env:
  - DB=sqlite
    # http://about.travis-ci.org/docs/user/database-setup/#MySQL
  - DB=mysql DB_CONNECTION="mysql2://root@localhost:3306/ccng"
    # http://about.travis-ci.org/docs/user/database-setup/#PostgreSQL
  - DB=postgres DB_CONNECTION="postgres://postgres@localhost:5432/ccng"

before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql  -c 'create database ccng;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ];    then mysql -e 'create database ccng;'; fi"

script: bundle exec rake spec
