---
port: 8181
pid_filename: /var/vcap/sys/run/cloud_controller.pid
nats_uri: nats://127.0.0.1:4222

bootstrap_admin_email: sre@vmware.com

logging:
  level: debug2

db:
  database: "sqlite:///tmp/cloud_controller.db"
  max_connections: 32
  pool_timeout: 10

uaa:
  resource_id: "cloud_controller"
  symmetric_secret: "tokensecret"

quota_manager:
  policy: "MoneyMakerApproval" # can also be BlindApproval
  base_url: "http://localhost:31004/v1/quota"
  auth_token: "testtoken"
  http_timeout_sec: 2
